version: "3.9"

services:
  mysql:
    container_name: db_service
    image: mysql:bsolutions
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: php_root
      MYSQL_DATABASE: b_solutions
      MYSQL_PASSWORD: php_root
    networks:
      - bsolution

  php:
    build:
      context: .
      dockerfile: ./apache.Dockerfile
    container_name: apache_service
    image: web:bsolutions
    volumes:
      - ./project:/var/www/html/
    ports:
      - 80:80
    networks:
      - bsolution

#Docker Networks
networks:
  bsolution:
    driver: bridge

volumes:
  mysql: {}
